[package]
name = "snake2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
log = "0.4"
winit = "0.26.1"
pixels = "0.9.0"
line_drawing = "1.0.0"
instant = "0.1.12"
rand = "0.8.4"